# Generated by Django 5.0.3 on 2024-03-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('New', 'New'), ('Recycled', 'Recycled')], default='New', max_length=20)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('battery_type', models.CharField(max_length=100)),
                ('form_factor', models.CharField(max_length=100)),
                ('mass', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('diameter', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='battery_images/')),
                ('nominal_voltage', models.FloatField(default=3.6)),
                ('nominal_energy', models.FloatField(default=16.2)),
                ('nominal_charge_capacity', models.FloatField(default=4.5)),
                ('voltage_range', models.CharField(default='2.5-4.2', max_length=100)),
                ('current_continuous', models.FloatField(default=8.61)),
                ('current_peak', models.FloatField(default=17.5)),
                ('power_continuous', models.FloatField(default=25.6)),
                ('power_peak', models.FloatField(default=50.0)),
                ('energy_density_gravimetric', models.FloatField(default=154)),
                ('energy_density_volumetric', models.FloatField(default=375)),
                ('power_density_gravimetric', models.FloatField(default=837)),
                ('power_density_volumetric', models.FloatField(default=2.04)),
                ('cell_id', models.CharField(default='9c9e4f9fc4', max_length=10, unique=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcode_images/')),
            ],
        ),
    ]
