# Generated by Django 5.0.3 on 2024-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterycell',
            name='cell_id',
            field=models.CharField(default='6f4276e50d', max_length=10, unique=True),
        ),
    ]
