# Generated by Django 5.0.3 on 2024-03-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_batterycell_cell_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batterycell',
            name='id',
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='cell_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('recycled', 'recycled')], default='new', max_length=20),
        ),
    ]
