# Generated by Django 5.0.3 on 2024-03-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_batterycell_id_alter_batterycell_cell_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batterycell',
            old_name='barcode',
            new_name='barcode_image',
        ),
    ]
