# Generated by Django 5.0.3 on 2024-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_barcode_batterycell_barcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batterycell',
            name='barcode_image',
        ),
        migrations.RemoveField(
            model_name='batterycell',
            name='image',
        ),
        migrations.AddField(
            model_name='batterycell',
            name='barcode_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterycell',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
