# Generated by Django 5.0.3 on 2024-03-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_batterycell_barcode_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterycell',
            name='cell_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
