# Generated by Django 5.0.3 on 2024-03-12 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_batterycell_cell_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterycell',
            name='cell_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
