# Generated by Django 5.0.3 on 2024-03-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_batterycell_cell_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterycell',
            name='cell_id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
