# Generated by Django 5.0.3 on 2024-03-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_batterycell_cell_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterycell',
            name='current_continuous',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='current_peak',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='energy_density_gravimetric',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='energy_density_volumetric',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='nominal_charge_capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='nominal_energy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='nominal_voltage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='power_continuous',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='power_density_gravimetric',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='power_density_volumetric',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='power_peak',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterycell',
            name='voltage_range',
            field=models.CharField(max_length=100),
        ),
    ]
